rotors:
  first:
    a: b
    b: c
    c: d
    d: e
    e: f
    f: g
    g: h
    h: i
    i: j
    j: k
    k: l
    l: m
    m: n
    n: o
    o: p
    p: q
    q: r
    r: s
    s: t
    t: u
    u: v
    v: w
    w: x
    x: y
    y: z
    z: a
  second:
    a: c
    b: d
    c: e
    d: f
    e: g
    f: h
    g: i
    h: j
    i: k
    j: l
    k: m
    l: n
    m: o
    n: p
    o: q
    p: r
    q: s
    r: t
    s: u
    t: v
    u: w
    v: x
    w: y
    x: z
    y: a
    z: b
  third:
    a: d
    b: e
    c: f
    d: g
    e: h
    f: i
    g: j
    h: k
    i: l
    j: m
    k: n
    l: o
    m: p
    n: q
    o: r
    p: s
    q: t
    r: u
    s: v
    t: w
    u: x
    v: y
    w: z
    x: a
    y: b
    z: c
reflector.pairs:
  1: 14
  2: 15
  3: 16
  4: 17
  5: 18
  6: 19
  7: 20
  8: 21
  9: 22
  10: 23
  11: 24
  12: 25
  13: 26
